[build]
  command = "npm install"
  functions = "functions"
  publish = "public"

[functions]
  # Increase the timeout for all functions to 26 seconds (generous for free tier)
  timeout = 26

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
