[build]
  command = "npm install"
  functions = "functions"
  publish = "public"

[functions]
  # No global timeout setting here

# Use a wildcard to apply settings to all functions
[functions."*"]
  timeout = 26

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
